AllCops:
  Exclude:
    - bin/*
    - db/*
    - db/**/*
    - vendor/bundle/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*.rake'
    - 'spec/*'
    - 'spec/**/*'
    - 'config/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'lib/tasks/*.rake'
    - 'spec/*'
    - 'spec/**/*'
    - 'config/*'

Style/Documentation:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false

Style/WordArray:
  Enabled: false
